name: "Danmu"
guid: "5B39DA44-5314-4940-8E26-54C821C17F86"
imageUrl: https://raw.githubusercontent.com/cxfksword/jellyfin-plugin-danmu/main/doc/logo.png
version: "1.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "cxfksword"
overview: "jellyfin弹幕下载插件"
description: >
  jellyfin的b站弹幕自动下载插件，会匹配b站番剧/电影视频，自动下载对应弹幕，并定时更新。
category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Danmu.dll"
changelog: >
  NA
