name: "🚀 Beta"

on:
  workflow_dispatch:

env:
  dotnet-version: 8.0.x
  python-version: 3.8
  project: Jellyfin.Plugin.Danmu/Jellyfin.Plugin.Danmu.csproj
  artifact: danmu

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Release

    steps:
      - uses: actions/checkout@v3
      - name: Inject DANDNA Api ID
        env:
          DANDAN_API_ID: ${{ secrets.DANDAN_API_ID }}
          DANDAN_API_SECRET: ${{ secrets.DANDAN_API_SECRET }}
        run: |
          sed -i "s/API_ID = \"\"/API_ID = \"$DANDAN_API_ID\"/g" Jellyfin.Plugin.Danmu/Scrapers/Dandan/DandanApi.cs
          sed -i "s/API_SECRET = \"\"/API_SECRET = \"$DANDAN_API_SECRET\"/g" Jellyfin.Plugin.Danmu/Scrapers/Dandan/DandanApi.cs
      - name: Get tags (For CHANGELOG)
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        id: dotnet
        with:
          dotnet-version: ${{ env.dotnet-version }}
      - name: Change default dotnet version
        run: |
          echo '{"sdk":{"version": "${{ steps.dotnet.outputs.dotnet-version }}"}}' > ./global.json
      - name: Initialize workflow variables
        id: vars
        run: |
          VERSION=$(echo "${GITHUB_REF#refs/*/}" | sed s/^v//)
          VERSION="$VERSION.0"
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "APP_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          dotnet restore ${{ env.project }} --no-cache
          dotnet publish --nologo --no-restore --configuration=Release --framework=net8.0 ${{ env.project }}
          mkdir -p artifacts
          cp ./Jellyfin.Plugin.Danmu/bin/Release/net8.0/Jellyfin.Plugin.Danmu.dll ./artifacts/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.vars.outputs.APP_NAME}}
          path: artifacts
          retention-days: 7
