name: "🚀 Publish Plugin"

on:
  push:
    tags: ["*"]

env:
  dotnet-version: 6.0.x
  python-version: 3.8
  artifact: danmu

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Release

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.dotnet-version }}
      - name: Restore nuget packages
        run: dotnet restore
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install JPRM
        run: python -m pip install jprm
      - name: Run JPRM
        run: python build_plugin.py --version=${GITHUB_REF#refs/*/}
      - name: Update release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifacts/${{ env.artifact }}_*.zip
          tag: ${{ github.ref }}
          file_glob: true
      - name: Update manifest
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update repo manifest
          file_pattern: manifest*.json
